import './globals.css';
import NavBar from '@/Components/Shared/NavBar';
import { Sora } from 'next/font/google';
import Footer from '../Components/AllPages/HomePage/Footer';

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${sora.className} h-full antialiased`}
    >
      <body className=" bg-[#F6F6F6] min-h-full flex flex-col">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
